import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { LightBlur } from "@/components/ui/LightBlur";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";
const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-darkest `}>
        <main className=" flex min-h-screen">
          <LightBlur />
          <div className="m-4 flex  flex-col items-center justify-between w-full">
            <header className="z-50 flex items-center justify-center p-4 mt-10 w-full">
              <Link href="/">
                <h1 className="text-6xl font-extrabold bg-gradient-to-r from-red-500 via-red-700 to-red-900 inline-block text-transparent bg-clip-text text-center">
                  Youtube Video Converter
                </h1>
              </Link>
            </header>
            {children}

            <footer>
              <p className="text-zinc-700 text-center">
                &copy; {new Date().getFullYear()} Youtube Video Converter
              </p>
            </footer>
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
